'use strict';
const assets=[{id:'CORE',name:'Core market',color:'#587ec2',price:100},{id:'TECH',name:'Technology',color:'#9367c4',price:100},{id:'HEALTH',name:'Healthcare',color:'#46a9a2',price:100},{id:'USD',name:'Demo dollars',color:'#bec9d6',price:1}];
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n),pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let balance=10000,selected='core',mode='explore',filter='all',trade=null,toastTimer;
const vaults=[];
function createVault(name,thesis,weights,manager='You · demo creator',id=crypto.randomUUID()){
 if(typeof name!=='string'||!name.trim()||name.trim().length>44||typeof thesis!=='string'||!thesis.trim()||thesis.trim().length>180)throw Error('Add a name and a short investment thesis.');
 if(!Array.isArray(weights)||weights.length!==4||weights.some(x=>!Number.isFinite(x)||x<0||x>100)||Math.abs(weights.reduce((a,b)=>a+b,0)-100)>1e-7)throw Error('Allocations must add up to 100%.');
 const v={id,name:name.trim(),thesis:thesis.trim(),weights:[...weights],manager,units:weights.map((w,i)=>10000*w/100/assets[i].price),supply:1000,userShares:0,cost:0,history:[10]};vaults.push(v);return v;
}
createVault('Market Mosaic','Broad equity exposure, spread across the core market, technology and healthcare.',[60,20,20,0],'Folio Research · demo manager','core');
createVault('Steady Mix','Half equities, half demo dollars. Explore how a reserve changes portfolio movements.',[30,10,10,50],'Folio Research · demo manager','mixed');
createVault('Tech Conviction','A focused technology allocation for investors comfortable with concentration.',[10,80,10,0],'Signal Studio · demo manager','tech');
function nav(v){return v.units.reduce((n,u,i)=>n+u*assets[i].price,0)}
function price(v){return nav(v)/v.supply}
function risk(v){return v.weights[3]>=40?'Mixed':Math.max(...v.weights.slice(0,3))>=75?'Concentrated':'Diversified'}
function current(){return vaults.find(v=>v.id===selected)}
function notify(s){$('toast').textContent=s;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4500)}
function selectVault(id){if(!vaults.some(v=>v.id===id))throw Error('Unknown strategy.');selected=id;render();return{id,price:price(current())}}
function chart(v){const h=v.history.length<2?[10,10]:v.history;let lo=Math.min(...h)-.15,hi=Math.max(...h)+.15;return `<svg class="chart" viewBox="0 0 280 78" role="img" aria-label="Simulated share price over ${v.history.length-1} market moves"><path d="M0 68H280" stroke="#e8edf3"/><polyline points="${h.map((n,i)=>`${i/(h.length-1)*280},${68-(n-lo)/(hi-lo)*58}`).join(' ')}" fill="none" stroke="#587ec2" stroke-width="2.5" stroke-linejoin="round"/></svg>`}
function render(){const invested=vaults.reduce((n,v)=>n+v.userShares*price(v),0);$('balance').textContent=money(balance);$('invested').textContent=money(invested);$('total').textContent=money(balance+invested);$('explore-nav').classList.toggle('active',mode==='explore');$('positions-nav').classList.toggle('active',mode==='positions');$('cards').hidden=mode!=='explore';$('positions').hidden=mode!=='positions';$('risk-filter').parentElement.hidden=mode!=='explore';$('section-name').firstChild.textContent=mode==='explore'?'Explore strategies ':'My positions ';const visible=vaults.filter(v=>filter==='all'||risk(v)===filter);$('count').textContent=mode==='explore'?visible.length:'';
$('cards').innerHTML=visible.length?visible.map((v,i)=>{let r=(price(v)/10-1)*100;return `<article class="card ${v.id===selected?'selected':''}"><div class="card-top"><div class="identity"><div class="emblem" style="--tint:${['#eaf0fb','#e9f4f0','#f0eafa'][i%3]};--color:${['#5072ad','#458673','#8b67ac'][i%3]}">${esc(v.name.charAt(0))}</div><div><h3>${esc(v.name)}</h3><span class="manager">${esc(v.manager)}</span></div></div><span class="badge">${risk(v)}</span></div><p>${esc(v.thesis)}</p><div class="card-bottom"><div class="metric"><label>Simulated return</label><strong class="${r<0?'negative':'positive'}">${pct(r)}</strong></div><div class="metric"><label>Demo vault value</label><strong>${money(nav(v))}</strong></div><button class="view-button" data-select="${v.id}" aria-label="View ${esc(v.name)}">View strategy ↗</button></div></article>`}).join(''):'<div class="empty">No strategies match this exposure. Try another filter.</div>';
const owned=vaults.filter(v=>v.userShares>1e-9);$('positions').innerHTML=owned.length?owned.map(v=>`<article class="position"><h3>${esc(v.name)}</h3><div class="row"><span>Current value</span><strong>${money(v.userShares*price(v))}</strong></div><div class="row"><span>Shares</span><strong>${v.userShares.toFixed(6)}</strong></div><div class="row"><span>Unrealized change</span><strong>${money(v.userShares*price(v)-v.cost)}</strong></div><button class="view-button" data-select="${v.id}">Manage position ↗</button></article>`).join(''):'<div class="empty"><h3>Your portfolio starts here.</h3>Invest demo dollars in a strategy to see your shares and performance.<br><button class="view-button" id="empty-explore">Explore strategies</button></div>';
const v=current(),p=price(v),r=(p/10-1)*100;$('detail').innerHTML=`<p class="eyebrow">STRATEGY DETAILS</p><h2 class="detail-heading">${esc(v.name)}</h2><p class="small">${esc(v.manager)}</p><div class="price">${money(p)}</div><span class="small">Per share · <span class="${r<0?'negative':'positive'}">${pct(r)}</span> since demo start</span>${chart(v)}<div class="row"><span>Market moves</span><strong>${v.history.length-1}</strong></div><hr class="line"><h3>Target allocation</h3><div class="allocation-bar">${v.weights.map((w,i)=>`<span style="width:${w}%;background:${assets[i].color}"></span>`).join('')}</div>${v.weights.map((w,i)=>w?`<div class="asset-row"><span><i class="dot" style="background:${assets[i].color}"></i>${assets[i].name}</span><strong>${w}%</strong></div>`:'').join('')}<p class="small">Weights can drift after market moves. Rebalancing is not automated in this demo.</p><hr class="line"><h3>Strategy rules</h3><div class="rules"><span>No leverage</span><span>4 allowed assets</span><span>0% demo fees</span></div><div class="row"><span>Your position</span><strong>${money(v.userShares*p)}</strong></div><button class="primary wide" data-trade="invest">Invest demo dollars</button>${v.userShares>1e-9?'<button class="secondary" data-trade="withdraw">Withdraw demo dollars</button>':''}`;
 document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{selectVault(b.dataset.select);if(window.innerWidth<731)$('detail').scrollIntoView({behavior:'smooth',block:'start'})});document.querySelectorAll('[data-trade]').forEach(b=>b.onclick=()=>openTrade(b.dataset.trade));if($('empty-explore'))$('empty-explore').onclick=()=>{mode='explore';render()};}
function marketMove(change){if(!Number.isFinite(change)||![-.05,.05].includes(change))throw Error('Choose a +5% or −5% demo move.');assets.slice(0,3).forEach(a=>a.price*=1+change);vaults.forEach(v=>v.history.push(price(v)));render();notify(`Simulated equities moved ${change>0?'+5%':'−5%'}. Portfolio values updated.`);return{change,balance,total:balance+vaults.reduce((n,v)=>n+v.userShares*price(v),0)}}
function openTrade(type){trade={type,id:selected};$('trade-form').reset();$('trade-error').textContent='';$('trade-type').textContent=type==='invest'?'INVEST DEMO FUNDS':'REDEEM YOUR SHARES';$('trade-name').textContent=current().name;$('confirm-trade').textContent=type==='invest'?'Confirm demo investment':'Confirm demo withdrawal';const max=tradeMax();$('available').textContent=`Available: ${money(max)}`;$('amount').max=(Math.floor((max+1e-8)*100)/100).toFixed(2);updatePreview();$('trade-dialog').showModal();$('amount').focus()}
function tradeMax(){const v=vaults.find(v=>v.id===trade.id);return trade.type==='invest'?balance:v.userShares*price(v)}
function updatePreview(){if(!trade)return;const v=vaults.find(v=>v.id===trade.id),amt=Number($('amount').value);$('trade-preview').innerHTML=`<div class="row"><span>Share price</span><strong>${money(price(v))}</strong></div><div class="row"><span>Shares ${trade.type==='invest'?'received':'redeemed'}</span><strong>${(Number.isFinite(amt)&&amt>0?amt/price(v):0).toFixed(6)}</strong></div><div class="row"><span>Demo fee</span><strong>$0.00</strong></div>`}
function transact(type,id,amount){const v=vaults.find(v=>v.id===id);if(!v||!['invest','withdraw'].includes(type)||!Number.isFinite(amount)||amount<=0||Math.abs(amount*100-Math.round(amount*100))>1e-6)throw Error('Enter a positive amount with at most two decimal places.');const p=price(v),limit=type==='invest'?balance:v.userShares*p;if(amount>limit+1e-8)throw Error('The amount exceeds your available balance.');const shares=amount/p;if(type==='invest'){const scale=(nav(v)+amount)/nav(v);v.units=v.units.map(u=>u*scale);v.supply+=shares;v.userShares+=shares;v.cost+=amount;balance-=amount}else{const scale=(nav(v)-amount)/nav(v);v.units=v.units.map(u=>u*scale);v.supply-=shares;v.cost*=Math.max(0,(v.userShares-shares)/v.userShares);v.userShares=Math.max(0,v.userShares-shares);balance+=amount}balance=Math.max(0,balance);render();return{type,amount,shares,remainingBalance:balance}}
$('trade-form').onsubmit=e=>{e.preventDefault();try{const result=transact(trade.type,trade.id,Number($('amount').value));$('trade-dialog').close();notify(`${money(result.amount)} ${result.type==='invest'?'invested':'withdrawn'} · ${result.shares.toFixed(4)} shares ${result.type==='invest'?'received':'redeemed'}.`)}catch(err){$('trade-error').textContent=err.message}};$('amount').oninput=updatePreview;$('max').onclick=()=>{$('amount').value=(Math.floor((tradeMax()+1e-8)*100)/100).toFixed(2);updatePreview()};
$('allocation-inputs').innerHTML=assets.map((a,i)=>`<label class="weight"><span><i class="dot" style="background:${a.color}"></i>${a.name} (%)</span><input aria-label="${a.name} allocation percent" class="weight-input" type="number" min="0" max="100" step="1" value="${[40,30,20,10][i]}" required></label>`).join('');function weights(){return Array.from(document.querySelectorAll('.weight-input')).map(x=>Number(x.value))}document.querySelectorAll('.weight-input').forEach(x=>x.oninput=()=>{const total=weights().reduce((a,b)=>a+b,0);$('weight-total').textContent=`${total}%`;$('weight-total').classList.toggle('invalid',total!==100)});
$('create-open').onclick=()=>{$('create-error').textContent='';$('create-dialog').showModal()};$('create-form').onsubmit=e=>{e.preventDefault();try{const data=new FormData(e.target),v=createVault(data.get('name'),data.get('thesis'),weights());selected=v.id;mode='explore';filter='all';$('risk-filter').value='all';render();$('create-dialog').close();notify('Strategy launched with $10,000 simulated seed capital.')}catch(err){$('create-error').textContent=err.message}};
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$(x.dataset.close).close());$('risk-filter').onchange=e=>{filter=e.target.value;render()};$('rally').onclick=()=>marketMove(.05);$('dip').onclick=()=>marketMove(-.05);$('explore-nav').onclick=()=>{mode='explore';render()};$('positions-nav').onclick=()=>{mode='positions';render()};render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const tools=[{name:'read_demo_portfolios',description:'Read simulated portfolios and demo cash. No real assets or live prices.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({balance,portfolios:vaults.map(v=>({id:v.id,name:v.name,sharePrice:price(v),userShares:v.userShares,weights:v.weights}))})},{name:'invest_demo_dollars',description:'Complete a simulated investment using the same demo account as the interface. No real funds.',inputSchema:{type:'object',properties:{id:{type:'string'},amount:{type:'number',exclusiveMinimum:0}},required:['id','amount'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{const r=transact('invest',input?.id,input?.amount);notify('Demo investment completed.');return r}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}}
